---
title: "R Notebook"
output:
  pdf_document: default
  pdf: default
---

```{r}
library(kernelboot)
library(boot)
library(dplyr)
library(ggplot2)
set.seed(123)
nsims <- 500
nstraps = 100
```

```{r}
# Define functions for calculating estimates (to simplify code)

# For Normal and Poisson
get_estimate_NormPois <- function(data, indices) {
  return(mean(data[indices]))
}

# For Binomial Distribution
get_estimate_Binom <- function(data, indices) {
  return(mean(data[indices]))
}

# For Geometric Distribution
get_estimate_Geom <- function(data, indices) {
  return(mean(data[indices]))
}

# For Exponential Distribution
get_estimate_Expo <- function(data, indices) {
  return(mean(data[indices]))
}

# Function for printing results
print_coverage <- function(data, widths) {
  # Get mean coverage probabilities
  vec <- c()
  for (i in 1:ncol(data)) {
     vec <- c(vec, mean(data[,i]))
  }
  # Get mean widths
  vec2 <- c()
  for (i in 1:ncol(widths)) {
     vec2 <- c(vec2, mean(widths[,i]))
  }
  
  tmp.df <- data.frame(matrix(ncol=2, nrow=15))
  colnames(tmp.df) <- c('coverage probability', 'average width')
  rownames(tmp.df) <- c('t-based 10', 't-based 30', 't-based 100',
                        'perc boot 10', 'perc boot 30', 'perc boot 100',
                        'basic boot 10', 'basic boot 30', 'basic boot 100',
                        'bca boot 10', 'bca boot 30', 'bca boot 100',
                        'smooth boot 10', 'smooth boot 30', 'smooth boot 100')
  tmp.df[,1] <- vec
  tmp.df[,2] <- vec2
  return(tmp.df)
}

get_bounds_df <- function(lowers, uppers) {
  # Get mean uppers
  vec <- c()
  for (i in 1:ncol(lowers)) {
     vec <- c(vec, mean(lowers[,i]))
  }
  # Get mean lowers
  vec2 <- c()
  for (i in 1:ncol(uppers)) {
     vec2 <- c(vec2, mean(uppers[,i]))
  }
  
  tmp.df <- data.frame(matrix(ncol=2, nrow=15))
  colnames(tmp.df) <- c('lower', 'upper')
  rownames(tmp.df) <- c('t-based 10', 't-based 30', 't-based 100',
                        'perc boot 10', 'perc boot 30', 'perc boot 100',
                        'basic boot 10', 'basic boot 30', 'basic boot 100',
                        'bca boot 10', 'bca boot 30', 'bca boot 100',
                        'smooth boot 10', 'smooth boot 30', 'smooth boot 100')
  
  tmp.df[,1] <- vec
  tmp.df[,2] <- vec2
  
  return(tmp.df)
}
```

\section{Normal Distribution Simulation}

```{r, warning = F, message=F}
# Create simulation variables
mu = 0

# Initialize Data Matrix
normies_coverage <- matrix(nrow = nsims, ncol = 15)
normies_width <- matrix(nrow = nsims, ncol = 15)
normies_lower <- matrix(nrow = nsims, ncol = 15)
normies_upper <- matrix(nrow = nsims, ncol = 15)

for (i in 1:nsims) {
  # Generate data of different sample sizes
  normies10 = rnorm(10)
  normies30 = rnorm(30)
  normies100 = rnorm(100)
  
  # Initialize row vector to be inserted into data matrix
  cov.i <- c()
  width.i <- c()
  lower.i <- c()
  upper.i <- c()
  
  #-----------------------------------------------------------------------------
  # Calculate t-based confidence intervals
  #-----------------------------------------------------------------------------
  
  # Construct t-based Lower and Upper bound CI for data of size n
  lower10t <- t.test(normies10, conf.level = 0.95)$conf.int[1]
  upper10t <- t.test(normies10, conf.level = 0.95)$conf.int[2]
  
  # Do the same for the rest of the n sample sizes
  lower30t <- t.test(normies30, conf.level = 0.95)$conf.int[1]
  upper30t <- t.test(normies30, conf.level = 0.95)$conf.int[2]
  
  lower100t <- t.test(normies100, conf.level = 0.95)$conf.int[1]
  upper100t <- t.test(normies100, conf.level = 0.95)$conf.int[2]
    
  # Get bool on whether confidence intervals contain the true parameter
  # and append that to cov.i, the row matrix we will add to the entire simulation's
  # Data Matrix
  cov.i <- c(cov.i, as.numeric((lower10t <= mu & upper10t >= mu)),
            (lower30t <= mu & upper30t >= mu),
            (lower100t <= mu & upper100t >= mu))
  
  width.i <- c(width.i, (upper10t - lower10t),
               (upper30t - lower30t),
               (upper100t - lower100t))
  
  lower.i <- c(lower.i, lower10t, lower30t, lower100t)
  upper.i <- c(upper.i, upper10t, upper30t, upper100t)
  
  #-----------------------------------------------------------------------------
  # Calculate Boot confidence intervals
  #-----------------------------------------------------------------------------
  
  # Create boot objects for the three sample sizes
  # These boot objects are used for the percentile, basic, and normal boot methods
  normies10.boot <- boot(
      data = normies10,
      statistic = get_estimate_NormPois,
      R = nstraps
  )
  normies30.boot <- boot(
      data = normies30,
      statistic = get_estimate_NormPois,
      R = nstraps
  )
  normies100.boot <- boot(
      data = normies100,
      statistic = get_estimate_NormPois,
      R = nstraps
  )
  
  # This whole loop calculates the three boot types in the list below
  boot_types <- c("perc", "basic", "bca")
  
  for (j in 1:(length(boot_types))) {
    subt <- 0
    if (boot_types[j] == "norm") {subt = 2}
    
    # Calculate lower and upper bounds for boot CI as before
    lower10 = boot.ci(normies10.boot, type = boot_types[j])[[4]][4-subt]
    upper10 = boot.ci(normies10.boot, type = boot_types[j])[[4]][5-subt]
    
    lower30 = boot.ci(normies30.boot, type = boot_types[j])[[4]][4-subt]
    upper30 = boot.ci(normies30.boot, type = boot_types[j])[[4]][5-subt]
    
    lower100 = boot.ci(normies100.boot, type = boot_types[j])[[4]][4-subt]
    upper100 = boot.ci(normies100.boot, type = boot_types[j])[[4]][5-subt]
    
    # Append whether the true parameter is covered to dataframe
    cov.i <- c(cov.i, (lower10 <= mu & upper10 >= mu),
               (lower30 <= mu & upper30 >= mu),
               (lower100 <= mu & upper100 >= mu))
    
    width.i <- c(width.i, (upper10 - lower10),
                (upper30 - lower30),
                (upper100 - lower100))
    
    lower.i <- c(lower.i, lower10, lower30, lower100)
    upper.i <- c(upper.i, upper10, upper30, upper100)
  }
  
  # Lastly, we calculate the 'Smooth' Bootstrap Confidence Intervals
  boot10 <- kernelboot(data=normies10, statistic=get_estimate_NormPois)
  lower10 <- summary(boot10)[3]; upper10 <- summary(boot10)[5]
  
  boot30 <- kernelboot(data=normies30, statistic=get_estimate_NormPois)
  lower30 <- summary(boot30)[3]; upper30 <- summary(boot30)[5]
  
  boot100 <- kernelboot(data=normies100, statistic=get_estimate_NormPois)
  lower100 <- summary(boot100)[3]; upper100 <- summary(boot100)[5]
  
  cov.i <- c(cov.i, (lower10 <= mu & upper10 >= mu),
               (lower30 <= mu & upper30 >= mu),
               (lower100 <= mu & upper100 >= mu))
  
  width.i <- c(width.i, (upper10 - lower10),
              (upper30 - lower30),
              (upper100 - lower100))
  
  lower.i <- c(lower.i, lower10, lower30, lower100)
  upper.i <- c(upper.i, upper10, upper30, upper100)
  # Set row of data matrix equal to the vector of data we calculated for this 
  # individual simulation
  
  normies_coverage[i,] <- cov.i
  normies_width[i,] <- width.i
  normies_lower[i,] <- lower.i
  normies_upper[i,] <- upper.i
}

# Print Coverage rate
print_coverage(normies_coverage, normies_width)  

```

## Create graph
```{r}
normies_bounds <- get_bounds_df(normies_lower, normies_upper)
#normies_bounds

group = c(rep("t-based", 3), rep("Percentile Bootstrap", 3), rep("Standard Bootstrap", 3), rep("BCA", 3), rep("Smooth Bootstrap", 3))

ci_data <- data.frame(ci_id = c(rownames(normies_bounds), rownames(normies_bounds)),
                      ci_bounds = c(normies_bounds$lower, normies_bounds$upper),
                      Method = c(group, group))
                      # capture_mu = c(ci$capture_mu, ci$capture_mu))


labels <- print_coverage(normies_coverage, normies_width)$'coverage probability'
labels <- c(rep(' ',15), labels)
ci_data$labels <- labels
ci_data <- ci_data %>%  
  mutate(name = factor(
    ci_id,
    levels = c(
      'smooth boot 100',
      'smooth boot 30',
      'smooth boot 10',
      'bca boot 100',
      'bca boot 30',
      'bca boot 10',
      'basic boot 100',
      'basic boot 30',
      'basic boot 10',
      'perc boot 100',
      'perc boot 30',
      'perc boot 10',
      't-based 100',
      't-based 30',
      't-based 10'
    )))

ci_data$Method <- factor(ci_data$Method, 
                         levels = c("t-based", "Percentile Bootstrap", 
                                    "Standard Bootstrap", "BCA", "Smooth Bootstrap"))

ggplot(data = ci_data, aes(x = ci_bounds, y = name, 
                       group = ci_id, color = Method)) +
  geom_point(size = 2) +  # add points at the ends, size = 2
  geom_line() +           # connect with lines
  geom_vline(xintercept = mu, color = "red") + # draw vertical line
  labs(x = "Confidence Interval Bounds",
       y = "Confidence Interval Methods",
       title = "Normal Distribution: Average Confidence Intervals ") +
  geom_text(aes(label=labels), hjust=1, vjust=1.5)

```


\section{Geometric Distribution Simulation}

```{r, warning = F, message=F}
# Create simulation variables
p = 0.15
mean = (1-p)/p

# Initialize Data Matrix
geomies_coverage <- matrix(nrow = nsims, ncol = 15)
geomies_width <- matrix(nrow = nsims, ncol = 15)
geomies_lower <- matrix(nrow = nsims, ncol = 15)
geomies_upper <- matrix(nrow = nsims, ncol = 15)

for (i in 1:nsims) {
#i = 3
  # Generate data of different sample sizes
  geomies10 = rgeom(10, p)
  geomies30 = rgeom(30, p)
  geomies100 = rgeom(100, p)
  
  # Initialize row vector to be inserted into data matrix
  cov.i <- c()
  width.i <- c()
  lower.i <- c()
  upper.i <- c()
  #-----------------------------------------------------------------------------
  # Calculate t-based confidence intervals
  #-----------------------------------------------------------------------------
  
  # Construct t-based Lower and Upper bound CI for data of size n
  lower10t <- t.test(geomies10, conf.level = 0.95, )$conf.int[1]
  upper10t <- t.test(geomies10, conf.level = 0.95)$conf.int[2]
  
  # Do the same for the rest of the n sample sizes
  lower30t <- t.test(geomies30, conf.level = 0.95)$conf.int[1]
  upper30t <- t.test(geomies30, conf.level = 0.95)$conf.int[2]
  
  lower100t <- t.test(geomies100, conf.level = 0.95)$conf.int[1]
  upper100t <- t.test(geomies100, conf.level = 0.95)$conf.int[2]
    
  # Get bool on whether confidence intervals contain the true parameter
  # and append that to cov.i, the row matrix we will add to the entire simulation's
  # Data Matrix
  cov.i <- c(cov.i, as.numeric((lower10t <= mean & upper10t >= mean)),
            (lower30t <= mean & upper30t >= mean),
            (lower100t <= mean & upper100t >= mean))
  
  width.i <- c(width.i, (upper10t - lower10t),
               (upper30t - lower30t),
               (upper100t - lower100t))
  
  lower.i <- c(lower.i, lower10t, lower30t, lower100t)
  upper.i <- c(upper.i, upper10t, upper30t, upper100t)
  #-----------------------------------------------------------------------------
  # Calculate Boot confidence intervals
  #-----------------------------------------------------------------------------
  
  # Create boot objects for the three sample sizes
  # These boot objects are used for the percentile, basic, and normal boot methods
  geomies10.boot <- boot(
      data = geomies10,
      statistic = get_estimate_Geom,
      R = nstraps
  )
  geomies30.boot <- boot(
      data = geomies30,
      statistic = get_estimate_Geom,
      R = nstraps
  )
  geomies100.boot <- boot(
      data = geomies100,
      statistic = get_estimate_Geom,
      R = nstraps
  )
  
  # This whole loop calculates the three boot types in the list below
  boot_types <- c("perc", "basic", "bca")
  
  for (j in 1:(length(boot_types))) {
    subt <- 0
    if (boot_types[j] == "norm") {subt = 2}
    
    if (sum(geomies10) == 0) {
      lower10 = 0
      upper10 = 0
    }
    else {
      # Calculate lower and upper bounds for boot CI as before
      lower10 = boot.ci(geomies10.boot, type = boot_types[j])[[4]][4-subt]
      upper10 = boot.ci(geomies10.boot, type = boot_types[j])[[4]][5-subt]
    }
    # Calculate lower and upper bounds for boot CI as before
    # lower10 = boot.ci(geomies10.boot, type = boot_types[j])[[4]][4-subt]
    # upper10 = boot.ci(geomies10.boot, type = boot_types[j])[[4]][5-subt]
    
    lower30 = boot.ci(geomies30.boot, type = boot_types[j])[[4]][4-subt]
    upper30 = boot.ci(geomies30.boot, type = boot_types[j])[[4]][5-subt]
    
    lower100 = boot.ci(geomies100.boot, type = boot_types[j])[[4]][4-subt]
    upper100 = boot.ci(geomies100.boot, type = boot_types[j])[[4]][5-subt]
    
    # Append whether the true parameter is covered to dataframe
    cov.i <- c(cov.i, (lower10 <= mean & upper10 >= mean),
               (lower30 <= mean & upper30 >= mean),
               (lower100 <= mean & upper100 >= mean))
    
    width.i <- c(width.i, (upper10 - lower10),
                (upper30 - lower30),
                (upper100 - lower100))
    
    lower.i <- c(lower.i, lower10, lower30, lower100)
    upper.i <- c(upper.i, upper10, upper30, upper100)
  }
  
  # Lastly, we calculate the 'Smooth' Bootstrap Confidence Intervals
  boot10 <- kernelboot(data=geomies10, statistic=get_estimate_NormPois)
  lower10 <- summary(boot10)[3]; upper10 <- summary(boot10)[5]
  
  boot30 <- kernelboot(data=geomies30, statistic=get_estimate_NormPois)
  lower30 <- summary(boot30)[3]; upper30 <- summary(boot30)[5]
  
  boot100 <- kernelboot(data=geomies100, statistic=get_estimate_NormPois)
  lower100 <- summary(boot100)[3]; upper100 <- summary(boot100)[5]
  
  cov.i <- c(cov.i, (lower10 <= mean & upper10 >= mean),
               (lower30 <= mean & upper30 >= mean),
               (lower100 <= mean & upper100 >= mean))
  
  width.i <- c(width.i, (upper10 - lower10),
              (upper30 - lower30),
              (upper100 - lower100))
  
  lower.i <- c(lower.i, lower10, lower30, lower100)
  upper.i <- c(upper.i, upper10, upper30, upper100)
  # Set row of data matrix equal to the vector of data we calculated for this 
  # individual simulation
  
  geomies_coverage[i,] <- cov.i
  geomies_width[i,] <- width.i
  geomies_lower[i,] <- lower.i
  geomies_upper[i,] <- upper.i
}

# Print Coverage rate
print_coverage(geomies_coverage, geomies_width)
```

Create graph

```{r}
geomies_bounds <- get_bounds_df(geomies_lower, geomies_upper)
geomies_bounds
p = 0.15
mean = (1-p)/p

group = c(rep("t-based", 3), rep("Percentile Bootstrap", 3), rep("Standard Bootstrap", 3), rep("BCA", 3), rep("Smooth Bootstrap", 3))

ci_data <- data.frame(ci_id = c(rownames(geomies_bounds), rownames(geomies_bounds)),
                      ci_bounds = c(geomies_bounds$lower, geomies_bounds$upper),
                      Method = c(group, group))
                      # capture_mu = c(ci$capture_mu, ci$capture_mu))
# Try to label pt2
labels <- print_coverage(geomies_coverage, geomies_width)$'coverage probability'
labels <- c(rep(' ',15), labels)
ci_data$labels <- labels

# ggplot(data = ci_data, aes(x = ci_bounds, y = ci_id,
#                            group = ci_id, color = Method)) +
#   geom_point(size = 2) +  # add points at the ends, size = 2
#   geom_line() +           # connect with lines
#   geom_vline(xintercept = mean, color = "red") + # draw vertical line
#   labs(x = "Confidence Interval Bounds",
#        y = "Confidence Interval Methods",
#        title = "Geometric Distribution: Average Confidence Intervals ") +
#   geom_text(aes(label=labels), hjust=1, vjust=1.5)

ci_data <- ci_data %>%  
  mutate(name = factor(
    ci_id,
    levels = c(
      'smooth boot 100',
      'smooth boot 30',
      'smooth boot 10',
      'bca boot 100',
      'bca boot 30',
      'bca boot 10',
      'basic boot 100',
      'basic boot 30',
      'basic boot 10',
      'perc boot 100',
      'perc boot 30',
      'perc boot 10',
      't-based 100',
      't-based 30',
      't-based 10'
    )))

ci_data$Method <- factor(ci_data$Method, levels = c("t-based", "Percentile Bootstrap", "Standard Bootstrap", "BCA", "Smooth Bootstrap"))

ggplot(data = ci_data, aes(x = ci_bounds, y = name, 
                       group = ci_id, color = Method)) +
  geom_point(size = 2) +  # add points at the ends, size = 2
  geom_line() +           # connect with lines
  geom_vline(xintercept = mean, color = "red") + # draw vertical line
  labs(x = "Confidence Interval Bounds",
       y = "Confidence Interval Methods",
       title = "Geometric Distribution: Average Confidence Intervals ") +
  geom_text(aes(label=labels), hjust=1, vjust=1.5)

```
\section{Exponential Distribution Simulation}

```{r, warning = F, message=F}
# Create simulation variables
lambda = 4
mean = 1/lambda

# Initialize Data Matrix
expos_coverage <- matrix(nrow = nsims, ncol = 15)
expos_width <- matrix(nrow = nsims, ncol = 15)
expos_lower <- matrix(nrow = nsims, ncol = 15)
expos_upper <- matrix(nrow = nsims, ncol = 15)

for (i in 1:nsims) {
  # Generate data of different sample sizes
  expos10 = rexp(10, lambda)
  expos30 = rexp(30, lambda)
  expos100 = rexp(100, lambda)
  
  # Initialize row vector to be inserted into data matrix
  cov.i <- c()
  width.i <- c()
  lower.i <- c()
  upper.i <- c()
  
  #-----------------------------------------------------------------------------
  # Calculate t-based confidence intervals
  #-----------------------------------------------------------------------------
  
  # Construct t-based Lower and Upper bound CI for data of size n
  lower10t <- t.test(expos10, conf.level = 0.95)$conf.int[1]
  upper10t <- t.test(expos10, conf.level = 0.95)$conf.int[2]
  
  # Do the same for the rest of the n sample sizes
  lower30t <- t.test(expos30, conf.level = 0.95)$conf.int[1]
  upper30t <- t.test(expos30, conf.level = 0.95)$conf.int[2]
  
  lower100t <- t.test(expos100, conf.level = 0.95)$conf.int[1]
  upper100t <- t.test(expos100, conf.level = 0.95)$conf.int[2]
    
  # Get bool on whether confidence intervals contain the true parameter
  # and append that to cov.i, the row matrix we will add to the entire simulation's
  # Data Matrix
  cov.i <- c(cov.i, as.numeric((lower10t <= mean & upper10t >= mean)),
            (lower30t <= mean & upper30t >= mean),
            (lower100t <= mean & upper100t >= mean))
  
  width.i <- c(width.i, (upper10t - lower10t),
               (upper30t - lower30t),
               (upper100t - lower100t))
  
  lower.i <- c(lower.i, lower10t, lower30t, lower100t)
  upper.i <- c(upper.i, upper10t, upper30t, upper100t)
  #-----------------------------------------------------------------------------
  # Calculate Boot confidence intervals
  #-----------------------------------------------------------------------------
  
  # Create boot objects for the three sample sizes
  # These boot objects are used for the percentile, basic, and normal boot methods
  expos10.boot <- boot(
      data = expos10,
      statistic = get_estimate_Expo,
      R = nstraps
  )
  expos30.boot <- boot(
      data = expos30,
      statistic = get_estimate_Expo,
      R = nstraps
  )
  expos100.boot <- boot(
      data = expos100,
      statistic = get_estimate_Expo,
      R = nstraps
  )
  
  # This whole loop calculates the three boot types in the list below
  boot_types <- c("perc", "basic", "bca")
  
  for (j in 1:(length(boot_types))) {
    subt <- 0
    if (boot_types[j] == "norm") {subt = 2}
    
    # Calculate lower and upper bounds for boot CI as before
    lower10 = boot.ci(expos10.boot, type = boot_types[j])[[4]][4-subt]
    upper10 = boot.ci(expos10.boot, type = boot_types[j])[[4]][5-subt]
    
    lower30 = boot.ci(expos30.boot, type = boot_types[j])[[4]][4-subt]
    upper30 = boot.ci(expos30.boot, type = boot_types[j])[[4]][5-subt]
    
    lower100 = boot.ci(expos100.boot, type = boot_types[j])[[4]][4-subt]
    upper100 = boot.ci(expos100.boot, type = boot_types[j])[[4]][5-subt]
    
    # Append whether the true parameter is covered to dataframe
    cov.i <- c(cov.i, (lower10 <= mean & upper10 >= mean),
               (lower30 <= mean & upper30 >= mean),
               (lower100 <= mean & upper100 >= mean))
    
    width.i <- c(width.i, (upper10 - lower10),
                (upper30 - lower30),
                (upper100 - lower100))
    
    lower.i <- c(lower.i, lower10, lower30, lower100)
    upper.i <- c(upper.i, upper10, upper30, upper100)
  }
  
  # Lastly, we calculate the 'Smooth' Bootstrap Confidence Intervals
  kernel.type = 'gaussian'
  boot10 <- kernelboot(data=expos10, statistic=get_estimate_NormPois, kernel = kernel.type)
  lower10 <- summary(boot10)[3]; upper10 <- summary(boot10)[5]
  
  boot30 <- kernelboot(data=expos30, statistic=get_estimate_NormPois, kernel = kernel.type)
  lower30 <- summary(boot30)[3]; upper30 <- summary(boot30)[5]
  
  boot100 <- kernelboot(data=expos100, statistic=get_estimate_NormPois, kernel = kernel.type)
  lower100 <- summary(boot100)[3]; upper100 <- summary(boot100)[5]
  
  cov.i <- c(cov.i, (lower10 <= mean & upper10 >= mean),
               (lower30 <= mean & upper30 >= mean),
               (lower100 <= mean & upper100 >= mean))
  
  width.i <- c(width.i, (upper10 - lower10),
              (upper30 - lower30),
              (upper100 - lower100))
  
  lower.i <- c(lower.i, lower10, lower30, lower100)
  upper.i <- c(upper.i, upper10, upper30, upper100)
  # Set row of data matrix equal to the vector of data we calculated for this 
  # individual simulation
  
  expos_coverage[i,] <- cov.i
  expos_width[i,] <- width.i
  expos_lower[i,] <- lower.i
  expos_upper[i,] <- upper.i
}

# Print Coverage rate
print_coverage(expos_coverage, expos_width)
```


```{r}
expos_bounds <- get_bounds_df(expos_lower, expos_upper)
expos_bounds
lambda = 4
mean = 1/lambda

group = c(rep("t-based", 3), rep("Percentile Bootstrap", 3), rep("Standard Bootstrap", 3), rep("BCA", 3), rep("Smooth Bootstrap", 3))

ci_data <- data.frame(ci_id = c(rownames(expos_bounds), rownames(expos_bounds)),
                      ci_bounds = c(expos_bounds$lower, expos_bounds$upper),
                      Method = c(group, group))
                      # capture_mu = c(ci$capture_mu, ci$capture_mu))

labels <- print_coverage(expos_coverage, expos_width)$'coverage probability'
labels <- c(rep(' ',15), labels)
ci_data$labels <- labels

# ggplot(data = ci_data, aes(x = ci_bounds, y = ci_id, 
#                            group = ci_id, color = Method)) +
#   geom_point(size = 2) +  # add points at the ends, size = 2
#   geom_line() +           # connect with lines
#   geom_vline(xintercept = mean, color = "red") + # draw vertical line
#   labs(x = "Confidence Interval Bounds",
#        y = "Confidence Interval Methods",
#        title = "Exponential Distribution: Average Confidence Intervals ") +
#   geom_text(aes(label=labels), hjust=1, vjust=1.5)

ci_data <- ci_data %>%  
  mutate(name = factor(
    ci_id,
    levels = c(
      'smooth boot 100',
      'smooth boot 30',
      'smooth boot 10',
      'bca boot 100',
      'bca boot 30',
      'bca boot 10',
      'basic boot 100',
      'basic boot 30',
      'basic boot 10',
      'perc boot 100',
      'perc boot 30',
      'perc boot 10',
      't-based 100',
      't-based 30',
      't-based 10'
    )))

ci_data$Method <- factor(ci_data$Method, levels = c("t-based", "Percentile Bootstrap", "Standard Bootstrap", "BCA", "Smooth Bootstrap"))

ggplot(data = ci_data, aes(x = ci_bounds, y = name, 
                       group = ci_id, color = Method)) +
  geom_point(size = 2) +  # add points at the ends, size = 2
  geom_line() +           # connect with lines
  geom_vline(xintercept = mean, color = "red") + # draw vertical line
  labs(x = "Confidence Interval Bounds",
       y = "Confidence Interval Methods",
       title = "Exponential Distribution: Average Confidence Intervals ") +
  geom_text(aes(label=labels), hjust=1, vjust=1.5)
```


\section{Poisson Distribution Simulation}

```{r, warning = F, message=F}
# Create simulation variables
lambda = 4

# Initialize Data Matrix
pois_coverage <- matrix(nrow = nsims, ncol = 15)
pois_width <- matrix(nrow = nsims, ncol = 15)
pois_lower <- matrix(nrow = nsims, ncol = 15)
pois_upper <- matrix(nrow = nsims, ncol = 15)

for (i in 1:nsims) {
  # Generate data of different sample sizes
  pois10 = rpois(10, lambda)
  pois30 = rpois(30, lambda)
  pois100 = rpois(100, lambda)
  
  # Initialize row vector to be inserted into data matrix
  cov.i <- c()
  width.i <- c()
  lower.i <- c()
  upper.i <- c()
  
  #-----------------------------------------------------------------------------
  # Calculate t-based confidence intervals
  #-----------------------------------------------------------------------------
  
  # Construct t-based Lower and Upper bound CI for data of size n
  lower10t <- t.test(pois10, conf.level = 0.95)$conf.int[1]
  upper10t <- t.test(pois10, conf.level = 0.95)$conf.int[2]
  
  # Do the same for the rest of the n sample sizes
  lower30t <- t.test(pois30, conf.level = 0.95)$conf.int[1]
  upper30t <- t.test(pois30, conf.level = 0.95)$conf.int[2]
  
  lower100t <- t.test(pois100, conf.level = 0.95)$conf.int[1]
  upper100t <- t.test(pois100, conf.level = 0.95)$conf.int[2]
    
  # Get bool on whether confidence intervals contain the true parameter
  # and append that to cov.i, the row matrix we will add to the entire simulation's
  # Data Matrix
  cov.i <- c(cov.i, as.numeric((lower10t <= lambda & upper10t >= lambda)),
            (lower30t <= lambda & upper30t >= lambda),
            (lower100t <= lambda & upper100t >= lambda))
  
  width.i <- c(width.i, (upper10t - lower10t),
               (upper30t - lower30t),
               (upper100t - lower100t))
  
  lower.i <- c(lower.i, lower10t, lower30t, lower100t)
  upper.i <- c(upper.i, upper10t, upper30t, upper100t)
  #-----------------------------------------------------------------------------
  # Calculate Boot confidence intervals
  #-----------------------------------------------------------------------------
  
  # Create boot objects for the three sample sizes
  # These boot objects are used for the percentile, basic, and normal boot methods
  pois10.boot <- boot(
      data = pois10,
      statistic = get_estimate_NormPois,
      R = nstraps
  )
  pois30.boot <- boot(
      data = pois30,
      statistic = get_estimate_NormPois,
      R = nstraps
  )
  pois100.boot <- boot(
      data = pois100,
      statistic = get_estimate_NormPois,
      R = nstraps
  )
  
  # This whole loop calculates the three boot types in the list below
  boot_types <- c("perc", "basic", "bca")
  
  for (j in 1:(length(boot_types))) {
    subt <- 0
    if (boot_types[j] == "norm") {subt = 2}
    
    # Calculate lower and upper bounds for boot CI as before
    lower10 = boot.ci(pois10.boot, type = boot_types[j])[[4]][4-subt]
    upper10 = boot.ci(pois10.boot, type = boot_types[j])[[4]][5-subt]
    
    lower30 = boot.ci(pois30.boot, type = boot_types[j])[[4]][4-subt]
    upper30 = boot.ci(pois30.boot, type = boot_types[j])[[4]][5-subt]
    
    lower100 = boot.ci(pois100.boot, type = boot_types[j])[[4]][4-subt]
    upper100 = boot.ci(pois100.boot, type = boot_types[j])[[4]][5-subt]
    
    # Append whether the true parameter is covered to dataframe
    cov.i <- c(cov.i, (lower10 <= lambda & upper10 >= lambda),
               (lower30 <= lambda & upper30 >= lambda),
               (lower100 <= lambda & upper100 >= lambda))
    
    width.i <- c(width.i, (upper10 - lower10),
                (upper30 - lower30),
                (upper100 - lower100))
    
    lower.i <- c(lower.i, lower10, lower30, lower100)
    upper.i <- c(upper.i, upper10, upper30, upper100)
  }
  
  # Lastly, we calculate the 'Smooth' Bootstrap Confidence Intervals
  boot10 <- kernelboot(data=pois10, statistic=get_estimate_NormPois)
  lower10 <- summary(boot10)[3]; upper10 <- summary(boot10)[5]
  
  boot30 <- kernelboot(data=pois30, statistic=get_estimate_NormPois)
  lower30 <- summary(boot30)[3]; upper30 <- summary(boot30)[5]
  
  boot100 <- kernelboot(data=pois100, statistic=get_estimate_NormPois)
  lower100 <- summary(boot100)[3]; upper100 <- summary(boot100)[5]
  
  cov.i <- c(cov.i, (lower10 <= lambda & upper10 >= lambda),
               (lower30 <= lambda & upper30 >= lambda),
               (lower100 <= lambda & upper100 >= lambda))
  
  width.i <- c(width.i, (upper10 - lower10),
              (upper30 - lower30),
              (upper100 - lower100))
  
  lower.i <- c(lower.i, lower10, lower30, lower100)
  upper.i <- c(upper.i, upper10, upper30, upper100)
  # Set row of data matrix equal to the vector of data we calculated for this 
  # individual simulation
  
  pois_coverage[i,] <- cov.i
  pois_width[i,] <- width.i
  pois_lower[i,] <- lower.i
  pois_upper[i,] <- upper.i
}

# Print Coverage rate
print_coverage(pois_coverage, pois_width)
```

```{r}
pois_bounds <- get_bounds_df(pois_lower, pois_upper)
pois_bounds
lambda = 4

group = c(rep("t-based", 3), rep("Percentile Bootstrap", 3), rep("Standard Bootstrap", 3), rep("BCA", 3), rep("Smooth Bootstrap", 3))

ci_data <- data.frame(ci_id = c(rownames(pois_bounds), rownames(pois_bounds)),
                      ci_bounds = c(pois_bounds$lower, pois_bounds$upper),
                      Method = c(group, group))
                      # capture_mu = c(ci$capture_mu, ci$capture_mu))

labels <- print_coverage(pois_coverage, pois_width)$'coverage probability'
labels <- c(rep(' ',15), labels)
ci_data$labels <- labels

# ggplot(data = ci_data, aes(x = ci_bounds, y = ci_id, 
#                            group = ci_id, color = Method)) +
#   geom_point(size = 2) +  # add points at the ends, size = 2
#   geom_line() +           # connect with lines
#   geom_vline(xintercept = lambda, color = "red") + # draw vertical line
#   labs(x = "Confidence Interval Bounds",
#        y = "Confidence Interval Methods",
#        title = "Poisson Distribution: Average Confidence Intervals ") +
#   geom_text(aes(label=labels), hjust=1, vjust=1.5)

ci_data <- ci_data %>%  
  mutate(name = factor(
    ci_id,
    levels = c(
      'smooth boot 100',
      'smooth boot 30',
      'smooth boot 10',
      'bca boot 100',
      'bca boot 30',
      'bca boot 10',
      'basic boot 100',
      'basic boot 30',
      'basic boot 10',
      'perc boot 100',
      'perc boot 30',
      'perc boot 10',
      't-based 100',
      't-based 30',
      't-based 10'
    )))

ci_data$Method <- factor(ci_data$Method, levels = c("t-based", "Percentile Bootstrap", "Standard Bootstrap", "BCA", "Smooth Bootstrap"))

ggplot(data = ci_data, aes(x = ci_bounds, y = name, 
                       group = ci_id, color = Method)) +
  geom_point(size = 2) +  # add points at the ends, size = 2
  geom_line() +           # connect with lines
  geom_vline(xintercept = lambda, color = "red") + # draw vertical line
  labs(x = "Confidence Interval Bounds",
       y = "Confidence Interval Methods",
       title = "Poisson Distribution: Average Confidence Intervals ") +
  geom_text(aes(label=labels), hjust=1, vjust=1.5)
```

\section{Binomial Distribution Simulation}

```{r, warning = F, message=F}
# Create simulation variables
p = 0.5
size = 50
mean = size*p

# Initialize Data Matrix
bin_coverage <- matrix(nrow = nsims, ncol = 15)
bin_width <- matrix(nrow = nsims, ncol = 15)
bin_lower <- matrix(nrow = nsims, ncol = 15)
bin_upper <- matrix(nrow = nsims, ncol = 15)

for (i in 1:nsims) {
  # Generate data of different sample sizes
  bin10 = rbinom(10, size, p)
  bin30 = rbinom(30, size, p)
  bin100 = rbinom(100, size, p)
  
  # Initialize row vector to be inserted into data matrix
  cov.i <- c()
  width.i <- c()
  lower.i <- c()
  upper.i <- c()
  
  #-----------------------------------------------------------------------------
  # Calculate t-based confidence intervals
  #-----------------------------------------------------------------------------
  
  # Construct t-based Lower and Upper bound CI for data of size n
  lower10t <- t.test(bin10, conf.level = 0.95)$conf.int[1]
  upper10t <- t.test(bin10, conf.level = 0.95)$conf.int[2]
  
  # Do the same for the rest of the n sample sizes
  lower30t <- t.test(bin30, conf.level = 0.95)$conf.int[1]
  upper30t <- t.test(bin30, conf.level = 0.95)$conf.int[2]
  
  lower100t <- t.test(bin100, conf.level = 0.95)$conf.int[1]
  upper100t <- t.test(bin100, conf.level = 0.95)$conf.int[2]
    
  # Get bool on whether confidence intervals contain the true parameter
  # and append that to cov.i, the row matrix we will add to the entire simulation's
  # Data Matrix
  cov.i <- c(cov.i, as.numeric((lower10t <= mean & upper10t >= mean)),
            (lower30t <= mean & upper30t >= mean),
            (lower100t <= mean & upper100t >= mean))
  width.i <- c(width.i, (upper10t - lower10t),
             (upper30t - lower30t),
             (upper100t - lower100t))
    
  lower.i <- c(lower.i, lower10t, lower30t, lower100t)
  upper.i <- c(upper.i, upper10t, upper30t, upper100t)
  #-----------------------------------------------------------------------------
  # Calculate Boot confidence intervals
  #-----------------------------------------------------------------------------
  
  # Create boot objects for the three sample sizes
  # These boot objects are used for the percentile, basic, and normal boot methods
  bin10.boot <- boot(
      data = bin10,
      statistic = get_estimate_Binom,
      R = nstraps
  )
  bin30.boot <- boot(
      data = bin30,
      statistic = get_estimate_Binom,
      R = nstraps
  )
  bin100.boot <- boot(
      data = bin100,
      statistic = get_estimate_Binom,
      R = nstraps
  )
  
  # This whole loop calculates the three boot types in the list below
  boot_types <- c("perc", "basic", "bca")
  
  for (j in 1:(length(boot_types))) {
    subt <- 0
    if (boot_types[j] == "norm") {subt = 2}
    
    # Calculate lower and upper bounds for boot CI as before
    lower10 = boot.ci(bin10.boot, type = boot_types[j])[[4]][4-subt]
    upper10 = boot.ci(bin10.boot, type = boot_types[j])[[4]][5-subt]
    
    lower30 = boot.ci(bin30.boot, type = boot_types[j])[[4]][4-subt]
    upper30 = boot.ci(bin30.boot, type = boot_types[j])[[4]][5-subt]
    
    lower100 = boot.ci(bin100.boot, type = boot_types[j])[[4]][4-subt]
    upper100 = boot.ci(bin100.boot, type = boot_types[j])[[4]][5-subt]
    
    # Append whether the true parameter is covered to dataframe
    cov.i <- c(cov.i, (lower10 <= mean & upper10 >= mean),
               (lower30 <= mean & upper30 >= mean),
               (lower100 <= mean & upper100 >= mean))
    width.i <- c(width.i, (upper10 - lower10),
              (upper30 - lower30),
              (upper100 - lower100))
    
    lower.i <- c(lower.i, lower10, lower30, lower100)
    upper.i <- c(upper.i, upper10, upper30, upper100)
  }
  
  # Lastly, we calculate the 'Smooth' Bootstrap Confidence Intervals
  boot10 <- kernelboot(data=bin10, statistic=get_estimate_NormPois)
  lower10 <- summary(boot10)[3]; upper10 <- summary(boot10)[5]
  
  boot30 <- kernelboot(data=bin30, statistic=get_estimate_NormPois)
  lower30 <- summary(boot30)[3]; upper30 <- summary(boot30)[5]
  
  boot100 <- kernelboot(data=bin100, statistic=get_estimate_NormPois)
  lower100 <- summary(boot100)[3]; upper100 <- summary(boot100)[5]
  
  cov.i <- c(cov.i, (lower10 <= mean & upper10 >= mean),
               (lower30 <= mean & upper30 >= mean),
               (lower100 <= mean & upper100 >= mean))
  width.i <- c(width.i, (upper10 - lower10),
              (upper30 - lower30),
              (upper100 - lower100))
  
  lower.i <- c(lower.i, lower10, lower30, lower100)
  upper.i <- c(upper.i, upper10, upper30, upper100)
  # Set row of data matrix equal to the vector of data we calculated for this 
  # individual simulation
  
  bin_coverage[i,] <- cov.i
  bin_width[i,] <- width.i
  bin_lower[i,] <- lower.i
  bin_upper[i,] <- upper.i
}

# Print Coverage rate
print_coverage(bin_coverage, bin_width)
```

```{r}
bin_bounds <- get_bounds_df(bin_lower, bin_upper)
bin_bounds
p = 0.5
size = 50
mean = size*p

group = c(rep("t-based", 3), rep("Percentile Bootstrap", 3), rep("Standard Bootstrap", 3), rep("BCA", 3), rep("Smooth Bootstrap", 3))

ci_data <- data.frame(ci_id = c(rownames(bin_bounds), rownames(bin_bounds)),
                      ci_bounds = c(bin_bounds$lower, bin_bounds$upper),
                      Method = c(group, group))
                      # capture_mu = c(ci$capture_mu, ci$capture_mu))

labels <- print_coverage(bin_coverage, bin_width)$'coverage probability'
labels <- c(rep(' ',15), labels)
ci_data$labels <- labels

ci_data <- ci_data %>%  
  mutate(name = factor(
    ci_id,
    levels = c(
      'smooth boot 100',
      'smooth boot 30',
      'smooth boot 10',
      'bca boot 100',
      'bca boot 30',
      'bca boot 10',
      'basic boot 100',
      'basic boot 30',
      'basic boot 10',
      'perc boot 100',
      'perc boot 30',
      'perc boot 10',
      't-based 100',
      't-based 30',
      't-based 10'
    )))

ci_data$Method <- factor(ci_data$Method, levels = c("t-based", "Percentile Bootstrap", "Standard Bootstrap", "BCA", "Smooth Bootstrap"))

ggplot(data = ci_data, aes(x = ci_bounds, y = name, 
                       group = ci_id, color = Method)) +
  geom_point(size = 2) +  # add points at the ends, size = 2
  geom_line() +           # connect with lines
  geom_vline(xintercept = mean, color = "red") + # draw vertical line
  labs(x = "Confidence Interval Bounds",
       y = "Confidence Interval Methods",
       title = "Binomial Distribution: Average Confidence Intervals ") +
  geom_text(aes(label=labels), hjust=1, vjust=1.5)
```

## Visualizing the generated data
```{r}
# 5 x 3 grid of generated data viz
par(mfrow = c(3, 3))

# Normal distribution (normal, continuous)
density_norm10 <- density(normies10)
plot(density_norm10, main = "Normal Distribution, n = 10")
density_norm30 <- density(normies30)
plot(density_norm30, main = "Normal Distribution, n = 30")
density_norm100 <- density(normies100)
plot(density_norm100, main = "Normal Distribution, n = 100")

# Binomial (normalish, discrete)
hist(bin10, main = "Binomial Distribution, n = 10")
hist(bin30, main = "Binomial Distribution, n = 30")
hist(bin100, main = "Binomial Distribution, n = 100")

# Geometric (skewed, discrete)
hist(geomies10, main = "Geometric Distribution, n = 10")
hist(geomies30, main = "Geometric Distribution, n = 30")
hist(geomies100, main = "Geometric Distribution, n = 100")

par(mfrow = c(2, 3))

# Poisson (skewed, discrete)
hist(pois10, main = "Poisson Distribution, n = 10")
hist(pois30, main = "Poisson Distribution, n = 30")
hist(pois100, main = "Poisson Distribution, n = 100")

# Exponential (skewed, continuous)
density_expo10 <- density(expos10)
plot(density_expo10, main = "Exponential Distribution, n = 10")
density_expo30 <- density(expos30)
plot(density_expo10, main = "Exponential Distribution, n = 30")
density_expo100 <- density(expos100)
plot(density_expo100, main = "Exponential Distribution, n = 100")
```

